using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PandorasBox.Gfx.SpirV
{
	public enum SpirVOpcodes
	{
		OpUnknown =			-1, // Don't know the instruction. (Out of the spec)

		// Miscellaneous
		OpNop =				0,
		OpUndef =			45,

		// Debug
		OpSource =			1,
		OpSourceExtension =	2,
		OpName =			54,
		OpMemberName =		55,
		OpString =			56,
		OpLine =			57,

		// Annotation
		OpDecorationGroup = 49,
		OpDecorate =		50,
		OpMemberDecorate =	51,
		OpGroupDecorate =	52,
		OpGroupMemberDecorate =	53,

		// Extension
		OpExtension =		3,
		OpExtInstImport =	4,
		OpExtInst =			44,

		// Mode-Setting
		OpMemoryModel =		5,
		OpEntryPoint =		6,
		OpExecutionMode =	7,
		OpCompileFlag =		218,

		// Type-Declaration
		OpTypeVoid =		8,
		OpTypeBool =		9,
		OpTypeInt =			10,
		OpTypeFloat =		11,
		OpTypeVector =		12,
		OpTypeMatrix =		13,
		OpTypeSampler =		14,
		OpTypeFilter =		15,
		OpTypeArray =		16,
		OpTypeRuntimeArray = 17,
		OpTypeStruct =		18,
		OpTypeOpaque =		19,
		OpTypePointer =		20,
		OpTypeFunction =	21,
		OpTypeEvent =		22,
		OpTypeDeviceEvent = 23,
		OpTypeReserveId =	24,
		OpTypeQueue =		25,
		OpTypePipe =		26,

		// Constant Creation
		OpConstantTrue =	27,
		OpConstantFalse =	28,
		OpConstant =		29,
		OpConstantComposite = 30,
		OpConstantSampler =	31,
		OpConstantNullPointer = 32,
		OpConstantNullObject = 33,
		OpSpecConstantTrue = 34,
		OpSpecConstantFalse = 35,
		OpSpecConstant =	36,
		OpSpecConstantComposite = 37,

		// Memory
		OpVariable =		38,
		OpVariableArray =	39,
		OpLoad =			46,
		OpStore =			47,
		OpCopyMemory =		65,
		OpCopyMemorySized =	66,
		OpAccessChain =		93,
		OpInBoundsAccessChain = 94,
		OpArrayLength =		121,
		OpImagePointer =	190,
		OpGenericPtrMemSemantics = 233,

		// Function
		OpFunction =		40,
		OpFunctionParameter = 41,
		OpFunctionEnd =		42,
		OpFunctionCall =	43,

		// Texture
		OpSampler =			67,
		OpTextureSample =	68,
		OpTextureSampleDref = 69,
		OpTextureSampleLod = 70,
		OpTextureSampleProj = 71,
		OpTextureSampleGrad = 72,
		OpTextureSampleOffset = 73,
		OpTextureSampleProjLod = 74,
		OpTextureSampleProjGrad = 75,
		OpTextureSampleLodOffset = 76,
		OpTextureSampleProjOffset = 77,
		OpTextureSampleGradOffset = 78,
		OpTextureSampleProjLodOffset = 79,
		OpTextureSampleProjGradOffset = 80,
		OpTextureFetchTexelLod = 81,
		OpTextureFetchTexelOffset = 82,
		OpTextureFetchSample = 83,
		OpTextureFetchTexel = 84,
		OpTextureGather =	85,
		OpTextureGatherOffset = 86,
		OpTextureGatherOffsets = 87,
		OpTextureQuerySizeLod = 88,
		OpTextureQuerySize =89,
		OpTextureQueryLod = 90,
		OpTextureQueryLevels = 91,
		OpTextureQuerySamples = 92,

		// Conversion
		OpConvertFToU =		100,
		OpConvertFToS =		101,
		OpConvertSToF =		102,
		OpConvertUToF =		103,
		OpUConvert =		104,
		OpSConvert =		105,
		OpFConvert =		106,
		OpConvertPtrToU =	107,
		OpConvertUToPtr =	108,
		OpPtrCastToGeneric = 109,
		OpGenericCastToPtr = 110,
		OpBitcast =			111,
		OpGenericCastToPtrExplicit = 232,
		OpSatConvertSToU =	263,
		OpSatConvertUToS =	264,

		// Composite
		OpVectorExtractDynamic = 58,
		OpVectorInsertDynamic = 59,
		OpVectorShuffle =		60,
		OpCompositeConstruct = 61,
		OpCompositeExtract = 62,
		OpCompositeInsert = 63,
		OpCopyObject =		64,
		OpTranspose =		112,

		// Arithmetic
		OpSNegate =			95,
		OpFNegate =			96,
		OpNot =				97,
		OpIAdd =			122,
		OpFAdd =			123,
		OpISub =			124,
		OpFSub =			125,
		OpIMul =			126,
		OpFMul =			127,
		OpUDiv =			128,
		OpSDiv =			129,
		OpFDiv =			130,
		OpUMod =			131,
		OpSRem =			132,
		OpSMod =			133,
		OpFRem =			134,
		OpFMod =			135,
		OpVectorTimesScalar = 136,
		OpMatrixTimesScalar = 137,
		OpVectorTimesMatrix = 138,
		OpMatrixTimesVector = 139,
		OpMatrixTimesMatrix = 140,
		OpOuterProduct =	141,
		OpDot =				142,
		OpShiftRightLogical = 143,
		OpShiftRightArithmetic = 144,
		OpShiftLeftLogical = 145,
		OpBitwiseOr =		149,
		OpBitwiseXor =		150,
		OpBitwiseAnd =		151,

		//Relational and Logical
		OpAny =				98,
		OpAll =				99,
		OpIsNan =			113,
		OpIsInf =			114,
		OpIsFinite =		115,
		OpIsNormal =		116,
		OpSignBitSet =		117,
		OpLessOrGreater =	118,
		OpOrdered =			119,
		OpUnordered =		120,
		OpLogicalOr =		146,
		OpLogicalXor =		147,
		OpLogicalAnd =		148,
		OpSelect =			152,
		OpIEqual =			153,
		OpFOrdEqual =		154,
		OpFUnordEqual =		155,
		OpINotEqual =		156,
		OpFOrdNotEqual =	157,
		OpFUnordNotEqual =	158,
		OpULessThan =		159,
		OpSLessThan =		160,
		OpFOrdLessThan =	161,
		OpFUnordLessThan =	162,
		OpUGreaterThan =	163,
		OpSGreaterThan =	164,
		OpFOrdGreaterThan =	165,
		OpFUnordGreaterThan = 166,
		OpULessThanEqual =	167,
		OpSLessThanEqual =	168,
		OpFOrdLessThanEqual = 169,
		OpFUnordLessThanEqual = 170,
		OpUGreaterThanEqual = 171,
		OpSGreaterThanEqual = 172,
		OpFOrdGreaterThanEqual = 173,
		OpFUnordGreaterThanEqual = 174,

		// Derivative
		OpDPdx =			175,
		OpDPdy =			176,
		OpFwidth =			177,
		OpDPdxFine =		178,
		OpDPdyFine =		179,
		OpFwidthFine =		180,
		OpDPdxCoarse =		181,
		OpDPdyCoarse =		182,
		OpFwidthCoarse =	183,

		// Flow Control
		OpPhi =				48,
		OpLoopMerge =		206,
		OpSelectionMerge =	207,
		OpLabel =			208,
		OpBranch =			209,
		OpBranchConditional = 210,
		OpSwitch =			211,
		OpKill =			212,
		OpReturn =			213,
		OpReturnValue =		214,
		OpUnreachable =		215,
		OpLifetimeStart =	216,
		OpLifetimeStop =	217,

		// Atomic
		OpAtomicInit =		191,
		OpAtomicLoad =		192,
		OpAtomicStore =		193,
		OpAtomicExchange =	194,
		OpAtomicCompareExchange = 195,
		OpAtomicCompareExchangeWeak = 196,
		OpAtomicIIncrement = 197,
		OpAtomicIDecrement = 198,
		OpAtomicIAdd =		199,
		OpAtomicISub =		200,
		OpAtomicUMin =		201,
		OpAtomicUMax =		202,
		OpAtomicAnd =		203,
		OpAtomicOr =		204,
		OpAtomicXor =		205,
		OpAtomicIMin =		265,
		OpAtomicIMax =		266,

		// Primitive
		OpEmitVertex =		184,
		OpEndPrimitive =	185,
		OpEmitStreamVertex = 186,
		OpEndStreamPrimitive = 187,

		// Barrier
		OpControlBarrier =	188,
		OpMemoryBarrier =	189,

		// Group
		OpAsyncGroupCopy =	219,
		OpWaitGroupEvents = 220,
		OpGroupAll =		221,
		OpGroupAny =		222,
		OpGroupBroadcast =	223,
		OpGroupIAdd =		224,
		OpGroupFAdd =		225,
		OpGroupFMin =		226,
		OpGroupUMin =		227,
		OpGroupSMin =		228,
		OpGroupFMax =		229,
		OpGroupUMax =		230,
		OpGroupSMax =		231,

		// Device-Side Enqueue
		OpEnqueueMarker =	249,
		OpEnqueueKernel =	250,
		OpGetKernelNDrangeSubGroupCount = 251,
		OpGetKernelNDrangeMaxSubGroupSize = 252,
		OpGetKernelWorkGroupSize = 253,
		OpGetKernelPreferredWorkGroupSizeMultiple = 254,
		OpRetainEvent =		255,
		OpReleaseEvent =	256,
		OpCreateUserEvent = 257,
		OpIsValidEvent =	258,
		OpSetUserEventStatus = 259,
		OpCaptureEventProfilingInfo = 260,
		OpGetDefaultQueue =		261,
		OpBuildNDRange =	262,

		// Pipe
		OpReadPipe =		234,
		OpWritePipe =		235,
		OpReservedReadPipe = 236,
		OpReservedWritePipe = 237,
		OpReserveReadPipePackets = 238,
		OpReserveWritePipePackets = 239,
		OpCommitReadPipe =	240,
		OpCommitWritePipe = 241,
		OpIsValidReserveId = 242,
		OpGetNumPipePackets = 243,
		OpGetMaxPipePackets = 244,
		OpGroupReserveReadPipePackets = 245,
		OpGroupReserveWritePipePackets = 246,
		OpGroupCommitReadPipe = 247,
		OpGroupCommitWritePipe = 248,
	}
}
